# 1. 列表、元组与字典

In [3]:
t = (10, 20, 30, 40)
print(t[-2:])          # 输出？
x, *y, z = t
print(y)               # 输出？

(30, 40)
[20, 30]


# 2. 文件操作

In [21]:
content = open ('example.txt').read()
content = content.split('\n')
contents=''
for index,j in enumerate( content ):
    contents+=( str( index) )
    contents+=(j)
    contents+=('\n')
contents
open ("output.txt",'w').write( contents )

101

# 3. NumPy基础

np.array()：最基础的方法，可将 Python 列表转换为 NumPy 矩阵，支持多维  
np.zeros()：创建指定形状的全零矩阵，默认数据类型为 float  
np.ones()：创建指定形状的全一矩阵   
np.eye(n)：创建 n×n 的单位矩阵（对角线为 1）   
np.arange() + reshape()：先创建有序序列，再调整为指定行列数  
np.random：生成随机值矩阵，常用的有rand()（均匀分布）和randn()（正态分布，初始方差为 1 ）  

筛选：matrix[条件]  
均值：           。mean()  
有点像pandas  

In [29]:
import numpy as np
matrixA = np.random.randint (low = 1 ,high =100,size =(10,10))
matrixA

array([[49, 36, 75, 37, 83, 77, 25,  3, 67, 56],
       [77, 98, 37, 76, 97, 86, 31, 92, 25, 47],
       [25, 80, 57, 61, 86, 62, 76, 26, 75, 73],
       [83, 41, 31, 72, 60, 94, 93, 61, 29, 94],
       [95, 23, 29, 11, 86,  6, 57, 54, 26, 19],
       [68, 57, 58, 59, 48, 76, 82, 32, 14, 77],
       [36, 51, 37, 68, 52,  1, 20, 22, 88, 79],
       [26, 23, 17, 62,  6, 41, 46, 53, 77, 30],
       [44, 96, 17,  7, 82, 15, 89, 73, 22, 87],
       [71, 33, 35, 99, 78, 89, 54, 26, 24, 88]], dtype=int32)

In [30]:
matrixB= np.eye(10)
matirxC = matrixA @ matrixB
matirxC

array([[49., 36., 75., 37., 83., 77., 25.,  3., 67., 56.],
       [77., 98., 37., 76., 97., 86., 31., 92., 25., 47.],
       [25., 80., 57., 61., 86., 62., 76., 26., 75., 73.],
       [83., 41., 31., 72., 60., 94., 93., 61., 29., 94.],
       [95., 23., 29., 11., 86.,  6., 57., 54., 26., 19.],
       [68., 57., 58., 59., 48., 76., 82., 32., 14., 77.],
       [36., 51., 37., 68., 52.,  1., 20., 22., 88., 79.],
       [26., 23., 17., 62.,  6., 41., 46., 53., 77., 30.],
       [44., 96., 17.,  7., 82., 15., 89., 73., 22., 87.],
       [71., 33., 35., 99., 78., 89., 54., 26., 24., 88.]])

In [32]:
matirxC [matirxC>80]=0
matirxC

array([[49., 36., 75., 37.,  0., 77., 25.,  3., 67., 56.],
       [77.,  0., 37., 76.,  0.,  0., 31.,  0., 25., 47.],
       [25., 80., 57., 61.,  0., 62., 76., 26., 75., 73.],
       [ 0., 41., 31., 72., 60.,  0.,  0., 61., 29.,  0.],
       [ 0., 23., 29., 11.,  0.,  6., 57., 54., 26., 19.],
       [68., 57., 58., 59., 48., 76.,  0., 32., 14., 77.],
       [36., 51., 37., 68., 52.,  1., 20., 22.,  0., 79.],
       [26., 23., 17., 62.,  6., 41., 46., 53., 77., 30.],
       [44.,  0., 17.,  7.,  0., 15.,  0., 73., 22.,  0.],
       [71., 33., 35.,  0., 78.,  0., 54., 26., 24.,  0.]])

值得注意，numpy和二维数组不一样，这里每一行内部不是数组关系，不可以使用  m[][]

In [39]:
m=matirxC [0:5,0:5]   

In [38]:
m.mean()

np.float64(35.08)

# 4. PyTorch基础

## 张量创建和属性

In [7]:
import torch
# 创建张量 A：形状 (3, 4)，元素为 [0, 11] 的整数
A = torch.arange(12).reshape(3, 4)
# 创建张量 B：形状 (3, 4)，服从标准正态分布
B = torch.randn(3,4)
B
# 判断以下操作是否正确：
#  A.shape #返回 torch.Size([3, 4])  正确
# (2) B.dtype 默认返回 torch.float32  正确
# (3) A.device 默认为 GPU  错误

tensor([[ 1.0520, -0.5471,  0.6003,  1.4072],
        [-0.4005,  1.0092, -0.1198,  1.5653],
        [ 1.4100,  0.6824, -1.1068,  2.1878]])

## 张量运算与广播

广播的「维度对齐优先级」:  
1.先给维度少的张量补全维度（从右向左补 1），使两者维度数量相同。  
2.再对每个维度从右向左检查：若维度大小不相等，只有其中一个为 1 时，才会将「1」扩展为另一个的大小。   
PS：如果step2中两边既不相等且都不是1，那么不满足广播规则，会报错  

In [ ]:
a = torch.tensor([[1], [2], [3]])  # shape (3, 1)
b = torch.tensor([4, 5, 6])        # shape (3,)\
# 计算 c = a + b，并写出 c 的形状
c = a+b   #3*3
# 计算 d = a * b，并解释广播规则  (广播过程会对)
d = a*b  #3*3